### ISSUE TITLE
use of credential_profile option fails to start

### ISSUE THREAD

**Issue by jjguy** [carbonblack/cb-event-forwarder#25] opened 2016-01-06 01:32 UTC
If using `credential_profile` option, cb-event-forwarder fails to start due to failure of the pre-start process:

```
Jan  6 00:28:08 localhost init: Connection from private client
Jan  6 00:28:08 localhost init: cb-event-forwarder goal changed from stop to start
Jan  6 00:28:08 localhost init: cb-event-forwarder state changed from waiting to starting
Jan  6 00:28:08 localhost init: Handling starting event
Jan  6 00:28:08 localhost init: cb-event-forwarder state changed from starting to pre-start
Jan  6 00:28:08 localhost init: cb-event-forwarder pre-start process (124932)
Jan  6 00:28:08 localhost init: cb-event-forwarder pre-start process (124932) terminated with status 1
Jan  6 00:28:08 localhost init: cb-event-forwarder goal changed from start to stop
Jan  6 00:28:08 localhost init: cb-event-forwarder state changed from pre-start to stopping
Jan  6 00:28:08 localhost init: Handling stopping event
Jan  6 00:28:08 localhost init: cb-event-forwarder state changed from stopping to killed
Jan  6 00:28:08 localhost init: cb-event-forwarder state changed from killed to post-stop
Jan  6 00:28:08 localhost init: cb-event-forwarder state changed from post-stop to waiting
Jan  6 00:28:08 localhost init: Handling stopped event
```

If we redirect output to a file, you see

```
[root@localhost cb-event-forwarder]# cat /tmp/blah.log
2016/01/06 01:18:20 Could not open bucket s3-cb-lts: UserHomeNotFound: user home directory not found.
[root@localhost cb-event-forwarder]#
```

if we explicitly set the `HOME` env variable in the init script it works:

```
pre-start script
 export HOME=/root
 /usr/share/cb/integrations/event-forwarder/cb-event-forwarder -check /etc/cb/integrations/event-forwarder/cb-event-forwarder.conf > /tmp/blah.log 2>&1
end script

script
  export HOME=/root
  /usr/share/cb/integrations/event-forwarder/cb-event-forwarder /etc/cb/integrations/event-forwarder/cb-event-forwarder.conf &> /var/log/cb/integrations/cb-event-forwarder/cb-event-forwarder.log
end script
```

**Comment by jgarman** [comment] 2016-01-07 15:25
Yep, this is because processes started from init don't have a $HOME. Oops. I think the only way to fix this in a generic fashion is to add another config option in the ini file to specify the location of the credential file; since you're the only one using the `credential_profile` option at the moment; would you mind if the existing option was changed to something like "file_path:profile_name"? For example:

```
[s3]
credential_profile=/opt/local/event-forwarder/.aws/credentials:profilename
```

**Comment by jjguy** [comment] 2016-01-07 18:58
@jgarman I support that approach.  ship it!

**Comment by jgarman** [comment] 2016-01-29 21:07
I will ship this in the next release 3.1.2

**Comment by jgarman** [comment] 2016-01-29 22:07
@jjguy, Take a look at 3.1.2 and close the issue if this works for you. Thanks!

**Comment by jgarman** [comment] 2016-03-15 20:47
Confirmed 3.1.2 fixed this issue

**Closed by jgarman** 2016-03-15 20:47 UTC
Labels: bug
