### ISSUE TITLE
cb event forwarder 3.8.0 does not send any events

### ISSUE THREAD

**Issue by jerome-kleinen-kbc-be** [carbonblack/cb-event-forwarder#221] opened 2022-01-11 19:33 UTC
Hello,

We use cb event forwarder to send raw cb events over a tcp output. We tried to update to version 3.8.0 but we noticed we completely stopped receiving any events. The configuration remained unchanged. We see no errors in the logs, but we can see that the tcp output simply isn't initialized.

Jerome

**Comment by zacharyestep** [comment] 2022-01-11 20:51
Hey Jerome! 

The 3.8.0 release contains some significant restructuring of the codebase so you might have hit a regression bug, but we did test the TCP output and ensure that's working (at least in a happy-path style test).

I'd like to start a conversation about this over email, could you please kindly reach out to me at zestep@vmware.com? 

Thanks :)

**Comment by jerome-kleinen-kbc-be** [comment] 2022-01-12 07:29
Hi Zachary,

I'll provide you some more details via email.

Thanks for the swift response.

Jerome

**Comment by zacharyestep** [comment] 2022-01-20 15:01
I believe some changes to how the connector logged caused the appearance of an issue (the daemon no longer logs to standard out but instead uses the configured log file after initial bootstrapping) but no underlying bug was found, closing. Thanks all.

**Closed as completed by zacharyestep** 2022-01-20 15:01 UTC

**Comment by jerome-kleinen-kbc-be** [comment] 2022-01-20 15:41
@zacharyestep - I am struggling to find the right words that accurately describe how much I disagree with your statement. I am simply blinded by rage that you brush this off as "the appearance of an issue" while I made it explicitly clear that the whole end-to-end data flow simply doesn't work anymore with the latest version you released. The absence of certain information on stdout was something I noticed and mentioned purely in the hope that it would help you to debug this issue.

Unfortunately, the way you are handling this issue is reminiscent of most of our other cases we opened via the official support portal.

**Comment by jjfallete** [comment] 2022-03-08 03:22
@zacharyestep I agree with @jeromekleinen-kbc and am disappointed that this was not addressed.

We just spent several days working with CB Support on this issue. CB Support has confirmed after evaluation that this is a defect and recommend we revert to v3.7.5 ... raw sensor events are not forwarded in v3.8.0

**Comment by jjfallete** [comment] 2022-03-08 19:47
Looks like this may be resolved in v3.8.1 -- awesome turnaround from this Support case!

Edit 3/14/21 - nevermind, this has not been resolved. Reverted back to 3.7.5

**Comment by jerome-kleinen-kbc-be** [comment] 2022-07-18 09:34
@jjfallete thanks for your input, I won't bother to try the 3.8.1. Funny how this issue was closed and not even reopened :)
